[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\n/home/agax)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc7\0\0\0M\0\0\ai\0\0\x4!\0\0\x3\xc7\0\0\0M\0\0\ai\0\0\x4!\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc7\0\0\0M\0\0\ai\0\0\x4!)

[FullScreen]
pos=@Point(560 1016)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(931 907)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/agax/Downloads/Black%20Myth_%20Wukong%20%E9%BB%91%E7%A5%9E%E8%AF%9D_%20%E6%82%9F%E7%A9%BA%20_%20SOUND%20TRACKS_%20%E5%BE%80%E7%94%9F%E5%92%92%20-%20Rebirth%20Mantra%20-%20DE%20Music.mp3, file:///home/agax/Videos/2024-07-25%2021-37-48.mkv, file:///home/agax/Videos/2024-07-25%2021-27-02.mkv, file:///home/agax/Videos/2024-07-25%2021-22-25.mkv
times=0, 65012, 0, 0
