-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

------------------
---- MONITORS ----
------------------

-- See https://wiki.hyprland.org/Configuring/Monitors/

--monitor=,preferred,auto,auto

-- source = ~/.config/hypr/monitors.conf -> requires manual conversion
local monitors = require("monitors")

-- source = ~/.config/hypr/workspaces.conf -> requires manual conversion
local workspaces = require("workspaces")

---------------------
---- MY PROGRAMS ----
---------------------

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"
local fileManager = "thunar"
local menu = "rofi -show drun -theme " .. os.getenv("HOME") .. "/.config/rofi/launchers/type-6/style-7.rasi"
local cliphist = "rofi -modi clipboard:"
	.. os.getenv("HOME")
	.. "/.config/cliphist/cliphist-rofi-img -theme "
	.. os.getenv("HOME")
	.. "/.config/rofi/launchers/type-6/style-7.rasi -show clipboard -show-icons"
local emoji = "rofi -modi emoji -theme "
	.. os.getenv("HOME")
	.. "/.config/rofi/launchers/type-2/style-1.rasi -show emoji -show-icons false"
local browser = "firefox"

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hyprland.org/Configuring/Environment-variables/
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("GBM_BACKEND", "nvidia-drm")

-- Unecessary to set for Hyprland-uwsm
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_CONFIG_HOME", os.getenv("HOME") .. "/.config")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("MOZ_ENABLE_WAYLAND", 1)

-- Hyprland / Wayland Java Fix
hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)

-- KDE QT 6 themeing and wayland support
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)
hl.env("QT_QPA_PLATFORM", "wayland")
--hl.env("QT_QPA_PLATFORM", "xcb")
hl.env("QT_QPA_PLATFORMTHEME", "hyprqt6engine")
hl.env("QT_QPA_PLATFORM_PLUGIN_PATH", "/usr/lib/qt/plugins/")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)
hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)

-- Android Path and emulator setting
hl.env("ANDROID_HOME", "/opt/android-sdk")

--cursor {
--    no_hardware_cursors = false
--}

-- Prevent XWayland scaling issues
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- Ensure steam is tiled on launch
--windowrulev2 = tile, class:(steam), title:(Steam)

-- Allow all other Steam windows (Friends, Settings, etc.) to float
--windowrulev2 = float, class:(steam), title:(?!Steam)

-- Floating rule for the emulator
--windowrulev2 = float, class:^(Emulator.*)$
--windowrulev2 = center, class:^(Emulator.*)$
--windowrulev2 = size 400 850, class:^(Emulator.*)$

-------------------
---- AUTOSTART ----
-------------------

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("udisksctl mount -b /dev/disk/by-label/primarystorage")
	hl.exec_cmd(
		"dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland"
	)
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME")
	hl.exec_cmd("thunar --daemon")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd(
		os.getenv("HOME") .. "/.config/awww/scripts/awww_loop.bash " .. os.getenv("HOME") .. "/.config/awww/wallpapers"
	)
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("dunst")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hypridle")
end)

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 20,
		border_size = 2,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		-- gold rgb(FFDE7C)
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = true,
		resize_corner = 1,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
		col = {
			active_border = { colors = { "rgb(A9D2D0)", "rgb(FFFFFF)", "rgb(A9D2D0)" }, angle = 90 },
			inactive_border = "rgba(595959aa)",
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 10,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = false,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = true,
		-- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.00 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "default" })

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
		-- You probably want this
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "us",
		follow_mouse = 1,
		sensitivity = 0.3,
		-- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = false,
		},
	},
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "F", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.float())

hl.bind(
	mainMod .. " + " .. "R",
	hl.dsp.exec_cmd("rofi -show drun -theme ${HOME}/.config/rofi/launchers/type-6/style-7.rasi")
)

hl.bind(mainMod .. " + " .. "F11", hl.dsp.window.fullscreen())

hl.bind(
	mainMod .. " + " .. "V",
	hl.dsp.exec_cmd(
		"rofi -modi clipboard:${HOME}/.config/cliphist/cliphist-rofi-img -theme ${HOME}/.config/rofi/launchers/type-6/style-7.rasi -show clipboard -show-icons"
	)
)

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("wlogout"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.exec_cmd("cliphist wipe"))

hl.bind(
	mainMod .. " + " .. "PERIOD",
	hl.dsp.exec_cmd(
		"rofi -modi emoji -theme ${HOME}/.config/rofi/launchers/type-2/style-1.rasi -show emoji -show-icons false"
	)
)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("hyprpicker -f hex -n -a"))
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp -d)" - | wl-copy'))

-- Volume control
hl.bind(mainMod .. " + " .. "F1", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/volume-notif/volume.sh decrement"))
hl.bind(mainMod .. " + " .. "F2", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/volume-notif/volume.sh increment"))
hl.bind(mainMod .. " + " .. "F3", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/volume-notif/volume.sh mute"))

-- Brightness control
hl.bind(mainMod .. " + " .. "F5", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/brightness.sh decrement"))
hl.bind(mainMod .. " + " .. "F6", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/brightness.sh increment"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

for i = 1, 10 do
	local key = i % 10
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Mouse bindings
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
