-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-05-16 at 15:43:49. Do not edit manually.

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "2560x1440@60.0",
    position = "2560x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "DP-2",
    mode     = "2560x1440@60.0",
    position = "0x0",
    scale    = 1.0,
})
