-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-05-16 at 15:42:58. Do not edit manually.

hl.workspace_rule({
	workspace = "1",
	monitor = "DP-2",
	default = true,
})

hl.workspace_rule({
	workspace = "2",
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = "3",
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = "4",
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = "5",
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = "6",
	monitor = "HDMI-A-1",
	default = true,
})

hl.workspace_rule({
	workspace = "7",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "8",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "9",
	monitor = "HDMI-A-1",
})

hl.workspace_rule({
	workspace = "10",
	monitor = "HDMI-A-1",
})
